### ISSUE TITLE
Upgrade to C#8

### ISSUE THREAD

**Issue by benaadams** [dotnet/arcade#1903]
Since preview 2 is out and it includes C#8 preview; the version of C# used should be upgraded so it can be dogfooded before release.

Currently it fails with https://github.com/dotnet/coreclr/pull/22272
```
CSC : error CS1617: Invalid option '8.0' for /langversion. 
Use '/langversion:?' to list supported values.
 [D:\j\workspace\x64_release_w---8f801950\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
```

**Comment by tannergooding** [comment]
This should be resolved by https://github.com/dotnet/buildtools/pull/2220, after arcade picks up the new buildtools build.

**Comment by markwilkie** [comment]
@tannergooding - what do you mean by arcade picking up the new buildtools build?  Is buildtools still determining which compiler corefx uses?

**Comment by markwilkie** [comment]
@tannergooding - buildtools is not the right place to make the change.  However, is there still more to do?

**Comment by tannergooding** [comment]
CoreFX/CoreCLR/CoreRT have all been upgraded to C# 8 (CoreCLR and CoreRT are still using BuildTools).

I don't think there is any further work for Arcade, unless you wanted to make it easier to opt-in to dogfooding Roslyn at the repo level.

**Comment by jaredpar** [comment]
@tannergooding 

> unless you wanted to make it easier to opt-in to dogfooding Roslyn at the repo level.

Can you elaborate on that? Arcade brings along a copy of the Roslyn compiler toolset so I'm not sure how to make that easier.

**Comment by tannergooding** [comment]
> Arcade brings along a copy of the Roslyn compiler toolset so I'm not sure how to make that easier.

@jaredpar. Right, but right now this:
* Defaults to `false`: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L47
* When `true`, defaults to `2.8.0`: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L54

It would be nice if arcade had a "set one property" mechanism for dogfooding things like Roslyn (or CoreCLR, CorefX, etc). That is, you set `UsingToolMicrosoftNetCompilers=dogfood` (or something similar) and it would:
* Use the toolset compiler that comes with arcade
* default the `LangVersion` to `preview`
* regularly update the included Toolset compiler (at each public preview, if nothing else)

**Comment by tannergooding** [comment]
Right now, repos using arcade and wanting to dogfood the latest Roslyn have to go through a multi-step process like: https://github.com/dotnet/corefx/pull/35134/files; just to get things cleanly working.

They then have to regularly update it themselves (https://github.com/dotnet/corefx/pull/35338) to keep things up-to-date.

**Comment by jaredpar** [comment]
@tannergooding 

> default the `LangVersion` to `preview`

I'm 100% against that being done. We've chatted with repository owners in the past and their feedback is pretty much universally that they're okay with being implicitly moved to stable releases of the language but don't want to be silently opting projects into previews.  

> * regularly update the included Toolset compiler (at each public preview, if nothing else)

Agree this should be done. My assumption is it would happen as a part of normal flow. 

I will be manually updating arcade toolse to the .NET Core Preview 3 compiler later this week. After that though I would expect automatic flow to take hold.

**Comment by tannergooding** [comment]
> but don't want to be silently opting projects into previews.

I 100% agree, that is why I suggested it be done via an explicit optin, but something that tells Arcade to handle it. i.e, you could have:
* `UsingToolMicrosoftNetCompilers=false` mean "just use what I have locally"
* `UsingToolMicrosoftNetCompilers=true` mean "use whatever Arcade ships with it, but don't opt-into new features" (currently 2.8.0, soon to be 3.0.0 Preview 3 from the sounds of it)
* `UsingToolMicrosoftNetCompilers=dogfood` mean `true` + "opt-into new features"
  * Maybe a better name is `DogfoodToolMicrosoftNetCompilers=true` (which would naturally default to false, but would give repos that one line opt-in).

The problem I see today is that, when a repo does want to dogfood, it takes multiple lines and then the repo becoming responsible for continuing to update the targeted ToolsetVersion. Getting this down to 1 or 2 lines and automatic updates would be significantly better.

**Comment by jaredpar** [comment]
@tannergooding 

> The problem I see today is that, when a repo does want to dogfood, it takes multiple lines and then the repo becoming responsible for continuing to update the targeted ToolsetVersion.

I agree it takes multiple lines but don't agree on the maintenance issue. Once you set LangVersion to Preview then you're done forever.

**Comment by tannergooding** [comment]
> Once you set LangVersion to Preview then you're done forever.

Fair enough.

**Comment by markwilkie** [comment]
You cool w/ closing this then @tannergooding ?
